# REVISÃO - NOÇÕES DE LÓGICA

## Proposição

Uma proposição é uma sentença declarativa que pode ser classificada como verdadeira ou falsa (V ou F). Exemplos de proposições:

-   "2 é um número par." (V)
-   "Dia 25 de dezembro é feriado." (V)
-   "A Terra é plana." (F)
-   "O Brasil é uma cidade." (F)

Uma proposição deve seguir os seguintes princípios:

-   Príncipio da Não-Contradição:

    Uma proposição não pode ser falsa e verdadeira ao mesmo tempo.

-   Princípio do Terceiro Excluído:

    Uma proposição só pode assumir o valor (V) de verdadeiro ou o valor (F) de falso, não havendo a possibilidade de assumir valores diferentes

## Linguagem

Chamamos de alfabeto de uma linguagem o conjunto de símbolos que a compôem. O alfabeto da lógica proposicional é constituída pelos seguintes símbolos:

-   Proposições são representadas por letras maiúsculas: (A, B, ...)

-   O símbolo de negação é representado por $\neg$

-   Conectivos lógicos são representados por $\land$, $\lor$, $\implies$, e $\iff$, significando, respectivamente:

    -   $\land$ - E (conjunção)
    -   $\lor$ - OU (disjunção)
    -   $\implies$ - SE...ENTÃO (implicação)
    -   $\iff$ - SE E SOMENTE SE (bicondicional)

-   Exemplo: Seja A = "Hoje é segunda-feira" e B = "Hoje é feriado".

    -   $\neg A$ - Hoje não é segunda-feira;
    -   $A \land B$ - Hoje é segunda-feira e é feriado;
    -   $A \lor B$ - Hoje é segunda-feira ou é feriado;
    -   $A \implies B$ - Se hoje é segunda-feira, então é feriado;
    -   $A \iff B$ - Hoje é segunda-feira se e somente se é feriado.

Os conectivos obedecem as regras do cálculo proposicional:

$$\begin{array}{|c c|c|c|c|c|}
p & q & p \land q & p \lor q & p \implies q & p \iff q\\
\hline
V & V & V & V & V & V\\
V & F & F & V & F & F\\
F & V & F & V & V & F\\
F & F & F & F & V & V\\
\end{array}$$

-   Exemplo: A = "Otávio é bombeiro" e B = "Otávio é advogado".

    -   $A \land B$ - "Otávio é bombeiro e advogado". Essa proposição só será verdadeira se Otávio for bombeiro e advogado ao mesmo tempo;
    -   $A \lor B$ - "Otávio é bombeiro ou advogado". Essa proposição será verdadeira se Otávio for bombeiro, advogado ou ambos;
    -   $A \implies B$ - "Se Otávio é bombeiro, então é advogado". Essa proposição será verdadeira se Otávio for bombeiro e advogado ao mesmo tempo, ou se Otávio não for bombeiro;
    -   $A \iff B$ - "Otávio é bombeiro se e somente se é advogado". Essa proposição será verdadeira se Otávio for bombeiro e advogado ao mesmo tempo, ou se Otávio não for bombeiro e nem advogado.

## Equivalências

-   $\neg \neg A\ = A$
-   $\neg(P \land Q) = (\neg P \lor \neg Q)$
-   $\neg(P \lor Q) = (\neg P \land \neg Q)$
-   $P \implies Q = (\neg P \lor Q)$

-   Exemplo: Seja A = "Hoje é segunda-feira" e B = "Hoje é feriado".

    -   $\neg \neg A$ - Hoje é segunda-feira;
    -   $\neg(A \land B)$ - Hoje não é segunda-feira ou não é feriado;
    -   $\neg(A \lor B)$ - Hoje não é segunda-feira e não é feriado;
    -   $A \implies B$ - Hoje não é segunda-feira ou é feriado.
    
## Tautologias e Contradições

Uma tautologia é uma proposição composta que é sempre verdadeira, independente dos valores das proposições simples que a compõem. Uma contradição é uma proposição composta que é sempre falsa, independente dos valores das proposições simples que a compõem.

-   Exemplo: Seja A = "Hoje é segunda-feira".

    -   $(A \lor \neg A)$ - Hoje é segunda-feira ou não é segunda-feira. Essa proposição é uma tautologia, pois sempre será verdadeira;
    -   $(A \land \neg A)$ - Hoje é segunda-feira e não é segunda-feira. Essa proposição é uma contradição, pois sempre será falsa.
