# EXPERIMENTOS E EVENTOS PROBABILÍSTICOS

## Experimento Aleatório

Iremos denominar pela letra grega $\varepsilon$ qualquer experimento aleatório realizado sob condições fixas. Vamos também chamar de **espaço amostral** ($\Omega$) o conjunto que contém todos os resultados possíveis de $\varepsilon$.

Aqui, "resultado possível" significa um resultado elementar e indivisível do experimento $\varepsilon$.

Exemplos:

**(i)** seja $\varepsilon_1$: lançar um dado honesto e observar o resultado (face voltada para cima)

$$
\begin{align*}
&\Omega_1=\{1,2,3,4,5,6\}\\
\end{align*}
$$
**(ii)** seja $\varepsilon_2$: medir a tensão de uma rede de alta tensão a cada minuto por uma hora.

$$
\begin{align*}
&\Omega_2=[0,+\infty)\\
\end{align*}
$$
**(iii)** seja $\varepsilon_3$: escolher um ponto do círculo unitário.

$$
\begin{align*}
&\Omega_3=\{(x,y)\in\mathbb{R}\;|\;x^2+y^2\le1\}\\
\end{align*}
$$

## Eventos

Eventos nada mais são do que conjuntos contendo elementos do espaço amostral que satisfazem dada condição. Em outras palavras, um evento é um subconjunto do espaço amostral.

Exemplo:

Para $\varepsilon_1$, podemos ter, por exemplo, os seguintes eventos:

$$
\begin{align*}
&A=\text{"oberva-se um número par"} = \{2,4,6\}\\
&B=\text{"oberva-se o número 2"} = \{2\}\\
&C=\text{"oberva-se um número maior ou igual a 4"} = \{4,5,6\}\\
&C=\text{"oberva-se um ímpar"} = \{1,3,5\}\\
\end{align*}
$$

Vamos denominar o conjunto $\phi$ a um evento impossível, e $\Omega$ a um evento certo.

Exemplo:

Para $\varepsilon_1$:

$A\cap D = \phi\rightarrow$ evento impossível.

$A\cup D = \Omega\rightarrow$ evento certo.

**DEFINIÇÃO: ** seja $\Omega$ o espaço amostral para o experimento $\varepsilon$, todo subconjunto $A\subset\Omega$ será chamado evento, como já mencionado, $\phi$ é o evento impossível e $\Omega$ é o evento certo. Se $\omega\in\Omega$, o evento $\{\omega\}$ é dito **elementar**.

## $\sigma$-álgebra

Para conseguirmos definir uma probabilidade precisaremos de uma classe especial de eventos chamada $\sigma$-álgebra, que representaremos pelo símbolo $\mathbb{A}$.

**DEFINIÇÃO: **seja $\mathbb{A}$ uma família de subconjuntos de $\Omega$ tal que:

**(i)**: $\Omega\in\mathbb{A}$.

**(ii)**: Se $A\in\mathbb{A}$, então $A^c\in\mathbb{A}$.

**(iii)**: Se $A_1,A_2,...\;\in\mathbb{A}$, então $\overset{\infty}{\underset{i=1}{\cup}}A_i\in\mathbb{A}$.

Nesse caso diremos que $\mathbb{A}$ é uma **$\sigma$-álgebra** sobre $\Omega$.

obs: Baseado em (i) e (ii), também podemos afirmar que $\phi\in\mathbb{A}$, já que $\phi$ é o complementar de $\Omega$.

Exemplos:

Para $\varepsilon_1$, $\Omega=\{1,2,3,4,5,6\}$.

Seja $\mathbb{A}_1=\{\{1\},\{1,2\},\{4,5,6\},\Omega,\phi\}$.

A condição (i) está satisfeita pois $\Omega\in\mathbb{A}_1$

A condição (ii) não está satisfeita pois os complementares de vários conjuntos não estão em $\mathbb{A}$

A condição (iii) não está satisfeita porque nem toda união de conjuntos dentro de $\mathbb{A}$ está dentro de $\mathbb{A}$. 

Agora, seja $\mathbb{A}_2=\{\{1,2\},\{3,4,5,6\},\Omega,\phi\}$

Em $\mathbb{A}_2$ podemos facilmente verificar que as três condições foram satisfeitas.
