# PROBABILIDADE

## Definição de uma Probabilidade

Existem varias formas de definir uma medida de probabilidade.

### Definição Clássica de Probabilidade

Suponha que $\Omega$ é finito e os pontos amostrais são equiprováveis.
Então define-se:
$$
\begin{align*}
&P(A) = \frac{\#(A)}{\#(\Omega)} 
\end{align*}
$$
Exemplo: para $\varepsilon_1$, $\Omega = \{1,2,3,4,5,6\}$, $A = \{2,4,6\}$, $B = \{2\}$, $C = \{4,5,6\}$  

$$
\begin{align*}
&P(A) = \frac{\#(A)}{\#(\Omega)} = \frac{3}{6} = \frac{1}{2} \\
&P(B) = \frac{\#(B)}{\#(\Omega)} = \frac{1}{6} \\
&P(C) = \frac{\#(C)}{\#(\Omega)} = \frac{3}{6} = \frac{1}{2}
\end{align*}
$$

### Definição Geométrica de Probabilidade

Seja $\varepsilon_2$: escolher aleatoriamente um ponto do intervalo (0,1).

$$
\begin{align*}
&\Omega = (0,1)
&P(A) = \frac{comp(A)}{comp(\Omega)}
\end{align*}
$$

$\varepsilon_3$ escolher um ponto no círculo unitário.

$$
\begin{align*}
&\Omega = \{(x,y)\;\epsilon\;\mathbb{R}²\;/\;x²+y²\le1\} \quad A = \{(x,y)\;\epsilon\;\mathbb{R}²\;/\;x²+y²\le\frac{1}{4}\} \\
&P(A) = \frac{área(A)}{área(\Omega)} = \frac{\pi\cdot\frac{1}{4}}{\pi} = \frac{1}{4} 
\end{align*}
$$

Em geral $P(A) = \frac{volume(A)}{volume(\Omega)}$

obs: Quando o $\Omega$ é contínuo, a probabilidade de qualquer ponto é 0.

### Definição Frequentista de Probabilidade

$\varepsilon$: Lançar uma moeda, não necessariamente honesta e registramos a ocorrência de cara.

$$
\begin{align*}
&A = \text{ocorrer cara} \\
&n = \text{número de lançamentos} \\
&P(A) = \frac{1}{n}\cdot(\text{número de ocorrência de A})
\end{align*}
$$

### Definição Axiomática de Probabilidade

Uma medida de probabilidade é uma função que satisfaz os três axiomas a seguir:

$$
\begin{align*}
&A_x1: P(A)\ge 0 \\
&A_x2:P(\Omega) = 1 \\
&A_x3:(\sigma\text{-aditividade}):Se\;A_1,A_2,...\text{são disjuntos então,}\;P(\overset{\infty}{\underset{i=1}{\cup}}A_i) = \overset{\infty}{\underset{i=1}{\Sigma}}P(A_i)
\end{align*}
$$

## Espaço de Probabilidade

Um espaço de probabilidade é um trio ($\Omega,\mathbb{A},P$) onde:

$$
\begin{align*}
&\Omega\text{ é um conjunto não-vazio} \\
&\mathbb{A} \text{ é uma } \sigma\text{-álgebra de subconjuntos de }\Omega \\
&P\text{ é uma probabilidade em }\mathbb{A}
\end{align*}
$$

## Propriedades de uma Probabilidade

$$
\begin{align*}
&P_1:\;P(A^c) = 1-P(A) \\
&P_2:\;0\le P(A)\le 1 \\
&P_3:\;P(B)=P(B\cap A)+P(B\cap A^c) \\
&P_4:\;\text{Se } A \subset B \rightarrow P(A)\le P(B) \\
&P_5:\;P(\overset{n}{\underset{i=1}{\cup}}A_i)\le \overset{n}{\underset{i=1}{\Sigma}}P(A_i) \\
&P_6:\;P(\overset{\infty}{\underset{i=1}{\cup}}A_i)\le \overset{\infty}{\underset{i=1}{\Sigma}}P(A_i) \\
&P_7:\;\text{(Continuidade de probabilidade) Se existe uma}\text{sequência }A_n\text{ tal que }A_n \uparrow A \text{ então }\\
&P(A_n) \uparrow P(A).\text{Analogamente, se }A_n \downarrow A \text{ entâo } P(A_n) \downarrow P(A)\\ \\
&P_8:\;P(A\cup B) = P(A) + P(B) - P(A\cap B). \\
&P(A\cup B\cup C) = P(A) + P(B) + P(C) - P(A\cap B) - P(A\cap C) - P(B\cap C) + P(A\cap B\cap C)
\end{align*}
$$

















