# PROBABILIDADE CONDICIONAL

## Definição de Probabilidade Condicional

Lembremos do experimento $\varepsilon_1$: lançar um dado.
$$
\begin{align*}
&\Omega = \{1,2,3,4,5,6\} \\
&\text{Seja A, sair número par } = \{2,4,6\} \text{ e B sair número maior que 3 } =\{4,5,6\} \\
&\text{Vimos que }P(A) = \frac{\#(A)}{\#(\Omega)} = \frac{1}{2} \\
&\text{A probabilidade de A, sabendo que ocorreu B, agora será }P(A) = \frac{\#(A\cap B)}{\#(B)} = \frac{2}{3}
\end{align*}
$$

Definição: Sejam A e B eventos aleatórios em $\mathbb{A}$. Define-se a probabilidade condicional de A dado B como $P(A|B)$.
$$
\begin{align*}
&P(A|B) = \frac{P(A\cap B)}{P(B)} \text{ se } P(B) > 0
\end{align*}
$$
Se $P(B) = 0, P(A|B) \text{ é arbitrário. Geralmente, nesse caso define-se P(A|B) = P(A)}$.

Importante: $P(qualquer coisa|B)$ é realmente uma medida de probabilidade, logo satisfaz todos os axiomas e propriedades de uma probabilidade.

Exemplos:
$$
\begin{align*}
&\bullet P(\Omega|B) \overset{def}{=} \frac{P(\Omega\cap B)}{P(B)} = \frac{P(B)}{P(B)} = 1 \\
&\bullet P((A\cup B)|C) = \frac{P((A\cup B)\cap C)}{P(C)} = \frac{P((A\cap C)\cup (B\cap C))}{P(C)} = \frac{P(A\cap C)}{P(C)} + \frac{P(B\cap C)}{P(C)} \\
&\bullet P(A|B) = \frac{P(A\cap B)}{P(B)} \text{ , também } P(B|A) =\frac{P(B\cap A)}{P(A)} = \frac{P(A\cap B)}{P(B)} \\
&\bullet P(A\cap B) = P(A|B)\cdot P(B) = P(B|A)\cdot P(A) \\
&\bullet P(A\cap B\cap C) = P(C|A\cap B)\cdot P(B|A)\cdot P(A)
\end{align*}
$$

## Teorema da Multiplicação

Os dois últimos resultados do exemplo anterior podem ser generalizados (teorema da multiplicação):

$$
\begin{align*}
&P(A_1\cap A_2\cap...\cap A_n) = P(A_1)\cdot P(A_2|A_1)...P(A_n|A_1\cap A_2\cap...\cap A_{n-1}) \\
&\forall A_1,A_2,...,A_n\;\epsilon \mathbb{A},\;n=2,3,...
\end{align*}
$$

Exemplo: Selecionar três cartas de um baralho, ao acaso e sem reposição. Qual a probabilidade de tirar 3 reis?

$$
\begin{align*}
&\text{Seja }A_i\text{ tirar um rei na i-ésima retirada. }i=(1,2,3) \\
&P(A_1\cap A_2\cap A_3) = P(A_1)\cdot P(A_2|A_1)\cdot P(A_3|A_1\cap A_2) = \frac{4}{52}\cdot \frac{3}{51}\cdot \frac{2}{50} \approx 0,000181
\end{align*}
$$

## Partição de Omega

Definição: Sejam $A_1,A_2,...$ subconjuntos de $\Omega$.
Diremos que os $A_i$'s formam uma partição de $\Omega$ se:

$$
\begin{align*}
&I)\;A_i\cap A_j = \phi\;, \forall i \neq j \;\text{(disjuntos)} \\
&II)\;\underset{i}{\cup}A_i = \Omega
\end{align*}
$$

## Teorema da Probabilidade Total

Seja $A_1,A_2,...$ uma partição de $\Omega$, então:

$$
\begin{align*}
&P(B)=\underset{i}{\Sigma}P(A_i)\cdot P(B|A_i), \forall B \;\epsilon\; \mathbb{A}
\end{align*}
$$

## Teorema de Bayes

Seja $A_1,A_2,...$ uma partição de $\Omega$, então:

$$
\begin{align*}
&P(A_i|B) = \frac{P(B|A_i)\cdot P(A_i)}{\underset{j}{\Sigma}P(B|A_j)\cdot P(A_j)}\;,\;\forall B\; \epsilon\; \mathbb{A},\; (i\text{ fixo})
\end{align*}
$$

Exemplo: Experimento de duas etapas ou composto.

Suponha que uma caixa contenha três moedas, duas honestas e uma de duas caras. Retirar uma moeda ao acaso e joga-la.Qual a probabilidade da moeda selecionada ter sido a de duas caras, dado que o resultado foi cara?

$$
\begin{align*}
&\text{Vamos definir os eventos:} \\
&A_1:\text{moeda retirada é honesta} \\
&A_2:\text{moeda retirada é de duas caras} \\
&B:\text{resultado é cara} \\
\\
&P(A_2|B) = \frac{P(B|A_2)\cdot P(A_2)}{P(B|A_1)\cdot P(A_1)+P(B|A_2)\cdot P(A_2)} = \frac{1\cdot \frac{1}{3}}{\frac{1}{2}\cdot\frac{2}{3}+1\cdot\frac{1}{3}} = \frac{\frac{1}{3}}{\frac{2}{3}} = \frac{1}{2}
\end{align*}
$$








































